CREATE TABLE IF NOT EXISTS users (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `username` TEXT UNIQUE NOT NULL,
  `password` TEXT NOT NULL,
  `status` INTEGER  NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tasks(
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `taskname` TEXT NOT NULL,
    `leader_id` INTEGER NOT NULL,
    `task_filepath` TEXT NOT NULL,
    `desc` TEXT,
    `status` INTEGER  NOT NULL DEFAULT 0,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files(
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `task_id` INTEGER NOT NULL,
    `file_name` TEXT NOT NULL,
    `file_path` TEXT  NOT NULL,
    `status` INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS scores(
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `task_id`  INTEGER  NOT NULL,
    `user_id` INTEGER  NOT NULL,
    `file_id` INTEGER NOT NULL,
    `score` FLOAT NOT NULL,
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

